package dev.redplate.workout

import androidx.activity.compose.BackHandler
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.ExperimentalLayoutApi
import androidx.compose.foundation.layout.FlowRow
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.statusBarsPadding
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.hilt.navigation.compose.hiltViewModel
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import dev.redplate.data.MuscleGroup
import dev.redplate.ui.components.PrimaryBar
import dev.redplate.ui.components.SearchField
import dev.redplate.ui.components.SegmentedToggle
import dev.redplate.ui.theme.RedplateTheme
import dev.redplate.ui.theme.RedplateType
import dev.redplate.ui.theme.StateColor
import kotlinx.coroutines.launch

// ── Route (stateful) ──────────────────────────────────────────────────────────

/**
 * The "I'll choose" path, in the order the design lays it out:
 * body map (5a) → generated session (3d) → browser (8c) when a row needs changing.
 *
 * Only the freestyle branch of the browser navigates away; swapping and adding edit the
 * stored template and come straight back to 3d, so what you inspected is what you start.
 */
@Composable
fun ExercisePickerRoute(
    onExerciseSelected: (sessionId: Long, exerciseId: String) -> Unit,
    modifier: Modifier = Modifier,
    viewModel: ExercisePickerViewModel = hiltViewModel(),
) {
    val phase by viewModel.phase.collectAsStateWithLifecycle()
    val isFrontView by viewModel.isFrontView.collectAsStateWithLifecycle()
    val muscleVolume by viewModel.muscleVolume.collectAsStateWithLifecycle()
    val pickedMuscles by viewModel.pickedMuscles.collectAsStateWithLifecycle()
    val pickedCount by viewModel.pickedCount.collectAsStateWithLifecycle()
    val query by viewModel.searchQuery.collectAsStateWithLifecycle()
    val generated by viewModel.generated.collectAsStateWithLifecycle()
    val browser by viewModel.browser.collectAsStateWithLifecycle()
    val scope = rememberCoroutineScope()

    // System back walks the phases instead of leaving the tab mid-build.
    BackHandler(enabled = phase != PickerPhase.MUSCLES) {
        when (phase) {
            PickerPhase.BROWSING -> viewModel.leaveBrowser()
            PickerPhase.GENERATED -> viewModel.backToMuscles()
            PickerPhase.MUSCLES -> Unit
        }
    }

    when (phase) {
        PickerPhase.MUSCLES -> MuscleSelectionScreen(
            isFrontView = isFrontView,
            muscleVolume = muscleVolume,
            pickedMuscles = pickedMuscles,
            pickedCount = pickedCount,
            searchQuery = query,
            onMuscleSelected = viewModel::toggleMuscle,
            onToggleView = viewModel::toggleView,
            onSearchChange = { text ->
                viewModel.search(text)
                // Typing is how you reach the archive behind the map.
                if (text.isNotBlank()) viewModel.browseFreestyle()
            },
            onBuildSession = viewModel::buildSession,
            modifier = modifier,
        )

        // The design's main path: the map produces a session you can read before the
        // first set, rather than dropping you into a flat list of exercises.
        PickerPhase.GENERATED -> GeneratedSessionScreen(
            state = generated,
            onSwapRow = viewModel::browseToSwap,
            onAddExercise = viewModel::browseToAdd,
            onSave = viewModel::backToMuscles,
            onStart = {
                scope.launch {
                    viewModel.startGeneratedSession()?.let { (sessionId, exerciseId) ->
                        onExerciseSelected(sessionId, exerciseId)
                    }
                }
            },
        )

        PickerPhase.BROWSING -> ExerciseBrowserScreen(
            state = browser,
            searchQuery = query,
            onSelect = viewModel::selectBrowsedExercise,
            onToggleFilter = viewModel::toggleBrowseFilter,
            onSearchChange = viewModel::search,
            onBack = viewModel::leaveBrowser,
            onConfirm = {
                scope.launch {
                    // Non-null only on the freestyle branch; swap and add stay put.
                    viewModel.commitBrowse()?.let { (sessionId, exerciseId) ->
                        onExerciseSelected(sessionId, exerciseId)
                    }
                }
            },
            modifier = modifier,
        )
    }
}

// ── Screen (stateless, 5a/5b design) ──────────────────────────────────────────

/**
 * Muscle group selection — design 5a/5b.
 *
 * The map is a status display as much as a control: every region is shaded against that
 * muscle's own weekly landmarks, so you see what is undertrained while deciding what to
 * train. Selection is multiple, and nothing commits until the bar at the bottom.
 */
@Composable
fun MuscleSelectionScreen(
    isFrontView: Boolean,
    muscleVolume: Map<MuscleGroup, VolumeLevel>,
    pickedMuscles: Set<MuscleGroup>,
    pickedCount: Int,
    searchQuery: String,
    onMuscleSelected: (MuscleGroup) -> Unit,
    onToggleView: () -> Unit,
    onSearchChange: (String) -> Unit,
    onBuildSession: () -> Unit,
    modifier: Modifier = Modifier,
) {
    val colors = RedplateTheme.colors

    Column(
        modifier = modifier
            .fillMaxSize()
            .background(colors.ground)
            .statusBarsPadding(),
    ) {
        Row(
            modifier = Modifier
                .fillMaxWidth()
                .padding(start = 20.dp, end = 20.dp, top = 16.dp, bottom = 8.dp),
            verticalAlignment = Alignment.Top,
            horizontalArrangement = Arrangement.SpaceBetween,
        ) {
            Text(
                text = "What are we\ntraining?",
                style = RedplateType.headline.copy(
                    fontSize = 27.sp,
                    lineHeight = 30.sp,
                    letterSpacing = (-0.015).sp,
                ),
                color = colors.ink,
                modifier = Modifier.weight(1f),
            )
            SegmentedToggle(
                options = listOf("FRONT", "BACK"),
                selectedIndex = if (isFrontView) 0 else 1,
                onOptionSelected = { onToggleView() },
            )
        }

        Box(
            modifier = Modifier
                .weight(1f)
                .fillMaxWidth(),
            contentAlignment = Alignment.Center,
        ) {
            BodyMapCanvas(
                isFrontView = isFrontView,
                volumeMap = muscleVolume,
                onMuscleSelected = onMuscleSelected,
                pickedMuscles = pickedMuscles,
                modifier = Modifier.fillMaxSize(),
            )
        }

        VolumeMapLegend(
            modifier = Modifier
                .fillMaxWidth()
                .padding(horizontal = 14.dp, vertical = 10.dp),
        )

        SearchField(
            query = searchQuery,
            onQueryChange = onSearchChange,
            placeholder = "Or search an exercise",
            modifier = Modifier
                .fillMaxWidth()
                .padding(horizontal = 16.dp)
                .padding(bottom = 8.dp),
        )

        PrimaryBar(
            label = if (pickedCount > 0) {
                "Build the session · $pickedCount picked"
            } else {
                "Tap what you want to train"
            },
            onClick = onBuildSession,
            enabled = pickedCount > 0,
            modifier = Modifier.padding(horizontal = 16.dp),
        )
    }
}

// ── Volume legend (the four map states of 5a) ────────────────────────────────

/**
 * The four map states, drawn from the same tokens [drawRegion] fills the body with, so
 * the key cannot drift from what it is describing.
 */
@OptIn(ExperimentalLayoutApi::class)
@Composable
private fun VolumeMapLegend(modifier: Modifier = Modifier) {
    val colors = RedplateTheme.colors

    FlowRow(
        horizontalArrangement = Arrangement.spacedBy(16.dp),
        verticalArrangement = Arrangement.spacedBy(7.dp),
        modifier = modifier,
    ) {
        LegendItem(label = "UNDER-TRAINED", textColor = colors.inkMuted) {
            Modifier.border(1.5.dp, colors.outlineDashed, SWATCH_SHAPE)
        }
        LegendItem(label = "ON TARGET", textColor = colors.inkMuted) {
            Modifier.background(colors.info.copy(alpha = 0.55f))
        }
        LegendItem(label = "NEAR CAP", textColor = colors.inkMuted) {
            Modifier.background(StateColor.pr.copy(alpha = 0.6f))
        }
        LegendItem(label = "PICKED", textColor = colors.ink) {
            Modifier
                .background(colors.ground)
                .border(3.dp, colors.ink, SWATCH_SHAPE)
        }
    }
}

@Composable
private fun LegendItem(
    label: String,
    textColor: Color,
    swatch: () -> Modifier,
) {
    Row(
        verticalAlignment = Alignment.CenterVertically,
        horizontalArrangement = Arrangement.spacedBy(7.dp),
    ) {
        Box(
            modifier = Modifier
                .size(12.dp)
                .clip(SWATCH_SHAPE)
                .then(swatch()),
        )
        Text(
            text = label,
            style = RedplateType.mono.copy(fontSize = 12.sp, letterSpacing = 0.04.sp),
            color = textColor,
        )
    }
}

private val SWATCH_SHAPE = RoundedCornerShape(3.dp)

// ── Previews ─────────────────────────────────────────────────────────────────

@Preview(name = "5a · front", showBackground = true, backgroundColor = 0xFF101317, widthDp = 384, heightDp = 824)
@Composable
private fun MuscleSelectionPreview() {
    RedplateTheme {
        MuscleSelectionScreen(
            isFrontView = true,
            muscleVolume = mapOf(
                MuscleGroup.CHEST to VolumeLevel.APPROACHING_MRV,
                MuscleGroup.BICEPS to VolumeLevel.BELOW_MEV,
                MuscleGroup.FRONT_DELTS to VolumeLevel.MEV_TO_MAV,
                MuscleGroup.ABS to VolumeLevel.MEV_TO_MAV,
                MuscleGroup.QUADS to VolumeLevel.BELOW_MEV,
            ),
            pickedMuscles = setOf(MuscleGroup.CHEST, MuscleGroup.BICEPS),
            pickedCount = 2,
            searchQuery = "",
            onMuscleSelected = {},
            onToggleView = {},
            onSearchChange = {},
            onBuildSession = {},
        )
    }
}

@Preview(name = "5b · back, nothing picked", showBackground = true, backgroundColor = 0xFF101317, widthDp = 384, heightDp = 824)
@Composable
private fun MuscleSelectionBackPreview() {
    RedplateTheme {
        MuscleSelectionScreen(
            isFrontView = false,
            muscleVolume = mapOf(
                MuscleGroup.TRAPS to VolumeLevel.APPROACHING_MRV,
                MuscleGroup.LATS to VolumeLevel.MEV_TO_MAV,
                MuscleGroup.GLUTES to VolumeLevel.MEV_TO_MAV,
                MuscleGroup.CALVES to VolumeLevel.MEV_TO_MAV,
            ),
            pickedMuscles = emptySet(),
            pickedCount = 0,
            searchQuery = "",
            onMuscleSelected = {},
            onToggleView = {},
            onSearchChange = {},
            onBuildSession = {},
        )
    }
}
